### ISSUE TITLE
无法访问https://captcha.saobby.tk/

### ISSUE THREAD

**Issue by wumingshiali** [Saobby/SaobbyCAPTCHAdoc#1]
访问captcha.saobby.tk会显示 
检查 captcha.saobby.tk 中是否存在拼写错误。
DNS_PROBE_FINISHED_NXDOMAIN
![](https://gp0.saobby.com/i/6K6ueoSZz0ePFksh.jpg)

**Comment by Saobby** [comment]
由于一些原因，这个展示站点很久之前就不可用了，如有需要请自行用源码搭建部署。

另外，这个验证码项目已不再维护，我自己的网站用的也是新做的v2版本验证码，但是v2版本还没来得及发在github，如有需要我有时间会发上来

**Comment by Saobby** [comment]
源码在这

https://github.com/Saobby/SaobbyCAPTCHARelease

**Comment by wumingshiali** [comment]
域名提供商被Facebook告是吧

**Comment by Gtd232** [comment]
> 域名提供商被Facebook告是吧

Freenom不再开放免费域名申请或续期了。
除非你发邮件给他们让他们同意，但更好的解决方案是买一个。
